#pragma once
#include "CoreMinimal.h"
#include "EMETA_LogCategory.generated.h"

UENUM(BlueprintType)
enum class EMETA_LogCategory : uint8 {
    None,
    Time = 5,
    Player = 41,
    Respect,
    BossLevel = 12,
    UI = 27,
    Save = 35,
    Difficulty = 40,
    Statistics = 26,
    Achievement = 37,
    Unlock_Reward = 28,
    Cash = 14,
    Blackmarket = 16,
    Equipment = 36,
    MarketLootEvent = 8,
    MarketWeaponEvent,
    MarketEquipmentEvent,
    Missions = 29,
    MoneyMakingOpportunities = 24,
    WeakenMissions = 39,
    JobManager = 34,
    Meta2FPS = 30,
    FPS2Meta,
    Ambush,
    TurfWar = 3,
    Gangs = 33,
    MarketHireArmyEvent = 11,
    Graph = 1,
    PlotlineSelection = 20,
    GoalManager = 38,
    RandEvent = 6,
    WarehouseAttack = 13,
    Heister = 2,
    MetaPerks = 7,
    HeisterPromotion = 19,
    NameGenerator = 15,
    RandomCharacterPool = 17,
    RevengePool,
    Stash = 4,
    PawnShop = 25,
    Heat = 21,
    PoliceInvestigation,
    Detective,
};

